### ISSUE TITLE
Does not account for near plane

### ISSUE THREAD

**Issue by jcowles** [keijiro/DepthToWorldPos#2]
It seems this:
https://github.com/keijiro/DepthInverseProjection/blob/4b3fec09ef82d3f5aeb44af36b8f72dec2e1cc07/Assets/InverseProjector.shader#L62

Does not account for the near clip plane, does it? That is, consider getting a depth value of zero -- that position should be at the near clip plane, but wont this math put it directly at the camera?

**Comment by keijiro** [comment]
It does. Linear01Depth is designed as it returns zero at the eye position; So it returns `near/far` at the near clip plane.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.

**Comment by jcowles** [comment]
Ah, I didn't realize, thanks!
