### ISSUE TITLE
Double multiplied by far clip plane

### ISSUE THREAD

**Issue by jcowles** [keijiro/DepthToWorldPos#3]
https://github.com/keijiro/DepthInverseProjection/blob/4b3fec09ef82d3f5aeb44af36b8f72dec2e1cc07/Assets/InverseProjector.shader#L39

Shouldn't the far clip plane already be accounted for by the inverse projection? Why is the ray multiplied by far again?

**Comment by keijiro** [comment]
No. `vpos` is on the near clip plane in the clip space, then `mul(unity_CameraInvProjection, vpos)` gives the positions of the near clip plane vertices. We can get the far vertices of the view frustum by multiplying it with `far`.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.

**Comment by jcowles** [comment]
That doesn't make sense to me, why would near * far = far?

I haven't done the math yet, but my hunch is that ray should be divided by W (after mul), but W is currently ignored. I check the math and report back, no need to reopen.
