### ISSUE TITLE
Missing namespaces

### ISSUE THREAD

**Issue by sourcetreehugger** [keijiro/DepthToWorldPos#4]
Hi,
I wanted to test your project but I cannot run it since there seem to be namespaces missing (screenshot). The readme says I only need Unity 2018.2 or higher.

Is there a component install or a library that I am missing? 

Found using
Unity 2018.2.0f2  (stock install)
Buildsettings: PC, Mac & Linux Standalone

![screenshot_3](https://user-images.githubusercontent.com/25456778/42683679-54189360-868e-11e8-962c-69986e6ffb60.png)

**Comment by sourcetreehugger** [comment]
I managed to fix this by using the package manager, but after importing the postprocessing, multiple scripts cannot be loaded since they were missing in the first place.

**Comment by keijiro** [comment]
I forgot to add the package manifest to the repo. Fixed in the latest commit.

**Comment by keijiro** [comment]
I'm closing the ticket. Please feel free to reopen for further questions.
