### ISSUE TITLE
Changing projection to a texture?

### ISSUE THREAD

**Issue by thunderawesome** [keijiro/DepthToWorldPos#5]
I know this is kind of old and maybe unsupported. I'm trying to modify this to project a texture of my choosing instead of projecting the lines by default. Any ideas?

**Comment by keijiro** [comment]
I'm not sure if I exactly understand what you meant, but I think it's better to use triplanar mapping for your situation.

https://github.com/keijiro/StandardTriplanar

This example is quite old. I'd recommend googling "triplanar mapping unity".
